### ISSUE TITLE
no assets :(

### ISSUE THREAD

**Issue by danilwhale** [JaanDev/MCRewrite#1]
![image](https://github.com/JaanDev/MCRewrite/assets/61111955/69df1cf8-9f0c-4045-bf2b-d4d8dcc16004)
:(

**Comment by danilwhale** [comment]
![image](https://github.com/JaanDev/MCRewrite/assets/61111955/d9bc8f00-34e4-4587-b06d-9ae4a73bb440)

**Comment by JaanDev** [comment]
Hi! Download this image and save it to `assets/terrain.png` near the game executable

![terrain](https://github.com/JaanDev/MCRewrite/assets/67502867/784a1699-eafc-4d4a-8c6d-5246f2844f9d)

**Comment by danilwhale** [comment]
will you plan updating this project?
